### ISSUE TITLE
Opening link leaves MFB with blank page

### ISSUE THREAD

**Issue by alekksander** [ZeeRooo/MaterialFBook#9]
Opening link from news feed sends link to browser, but leaves application with blank white page.

**Comment by ZeeRooo** [comment]
It was fixed in version v2.1.0
Enjoy :)

**Comment by alekksander** [comment]
Sweet :)

**Comment by ZeeRooo** [comment]
Its working good now?

**Comment by alekksander** [comment]
yes, but still not perfectly. now when link opens, there is less flickering and chaos, but app never returns in to the position it was before link was clicked. for example, if i click link from newsfeed, link is sent to browser, but position in newsfeed is set to random place (usually somewhere at the top). desired behavior is for the app to return to the same place it was before click — just like it happens when You open link without leaving application (facebook article) — somehow it returns to the exact same place when going back.

i hope i presented the problem in understandable manner 😄

**Comment by ZeeRooo** [comment]
Yes, i i know. I use webview.goback (same result touching 2 times the back
button), im going to try fix the problem later.

**Comment by ZeeRooo** [comment]
It was **fully** fixed in **v2.5.0**

You can **download** it from here: https://raw.githubusercontent.com/ZeeRooo/MaterialFBook/master/apks/MaterialFBook_2.5.0.apk

_Yes, too late... i know_
